### ISSUE TITLE
Update Android SDK from 0.5.1 to 1.0.3

### ISSUE THREAD

**Issue by mtelle** [Estimote/Xamarin-Bindings#12]
Hi,

I want to start a project using estimote and xamarin, but this bindings are using 0.5.1.
I am trying to update them but i could´t get a it.

Someone has tried with good results?

**Comment by heypiotr** [comment]
Done in https://github.com/Estimote/Xamarin-Bindings/commit/0426579694180ab2bbf2830c6fc77863b1261466.
