### ISSUE TITLE
Update NuGet for iOS 12 with new Swift4 packages

### ISSUE THREAD

**Issue by MatthewGerber** [Estimote/Xamarin-Bindings#14]
I believe the NuGet for this needs to be updated for iOS 12 with the new Swift4 packages. When might we expect this?

**Comment by heypiotr** [comment]
Done! https://github.com/Estimote/Xamarin-Bindings/commit/61db3a493964a0379493276ecc65ae607842c980

NuGet package:
https://www.nuget.org/packages/Estimote.iOS.Proximity/1.2.0
