### ISSUE TITLE
Estimote Indoor and Proximity bindings include different Kotlin versions

### ISSUE THREAD

**Issue by MatthewGerber** [Estimote/Xamarin-Bindings#18]
I'm separating this issue from #17 where I first observed it. Here's the problem as I see it.

The Proximity and Indoor binding projects include different versions of the Kotlin JARs. As a result, including both binding NuGets in an app results in the following compilation error:

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: java.lang.IllegalArgumentException: already added :  Lkotlin/ArrayIntrinsicsKt;
```

Apparently, if the Kotlin JAR files are made to be the same version across the two binding projects, then the compiler is smart enough to only process the JARs from one of the NuGets, thus resolving the "already loaded" error. I'll post a PR fixing this shortly.

**Comment by heypiotr** [comment]
Just for book-keeping, the relevant PR is here: https://github.com/Estimote/Xamarin-Bindings/pull/19
