### ISSUE TITLE
Android IndoorLocationView throws NoClassDefFoundError

### ISSUE THREAD

**Issue by MatthewGerber** [Estimote/Xamarin-Bindings#20]
@heypiotr When using the Android Indoor binding NuGet (v2.5.4.1), everything works as expected until I attempt to display the `Estimote.Android.Indoor.IndoorLocationView`. Upon display, the attached exception is thrown:

<img width="748" alt="screen shot 2019-01-07 at 11 09 31 am" src="https://user-images.githubusercontent.com/4643066/50779185-ade96480-126d-11e9-9245-553e05cb3a9f.png">

It looks like the resources class (named `R`) hasn't been included in the Indoor SDK project and is therefore missing from the Android Indoor binding NuGet. Can you please confirm and update the Android Indoor binding NuGet accordingly? Thanks!

**Comment by heypiotr** [comment]
Fixed in 2.5.4.2:

https://www.nuget.org/packages/Estimote.Android.Indoor/2.5.4.2
