### ISSUE TITLE
Estimote.Android.Proximity doesn't build with latest xamarin.

### ISSUE THREAD

**Issue by jramstedt** [Estimote/Xamarin-Bindings#23]
This is propably because I'm using Xamarin.Android.Support.Annotations version 28.0.0.1.

After adding Estimote.Android.Proximity NuGet package I'm getting following build errors:

2>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnimRes;
2>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnimatorRes;
2>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnyRes;
2>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnyThread;
2>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/ArrayRes;
2>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AttrRes;
2>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/BinderThread;
2>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/BoolRes;
2>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/CallSuper;
2>  
2>  UNEXPECTED TOP-LEVEL EXCEPTION:
2>  java.lang.RuntimeException: Translation has been interrupted
2>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
2>  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
2>  	at com.android.dx.command.dexer.Main.run(Main.java:277)
2>  	at com.android.dx.command.dexer.Main.main(Main.java:245)
2>  	at com.android.dx.command.Main.main(Main.java:106)
2>  Caused by: java.lang.InterruptedException: Too many errors
2>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
2>  	... 4 more

**Comment by heypiotr** [comment]
Right, we package our own support-annotations, so there's a conflict.

This was actually fixed by @jabusjavus in https://github.com/Estimote/Xamarin-Bindings/pull/21 and https://github.com/Estimote/Xamarin-Bindings/pull/22, which are already merged to master, I just haven't gotten around to releasing updates NuGet packages yet. I'll try to do this early next week.

In the meantime, you can clone this repo, and built an updated NuGet package for yourself.

**Comment by heypiotr** [comment]
Uploaded new packages to NuGet—they seem to work for me, let us know!
