### ISSUE TITLE
WithTelemetryReporting is missing

### ISSUE THREAD

**Issue by MatthewGerber** [Estimote/Xamarin-Bindings#3]
When configuring the `IProximityObserver`, it looks like the `WithTelemetryReporting` method is missing from the class. Was it accidentally left out of the binding?

**Comment by heypiotr** [comment]
The binding currently uses Android Proximity SDK 0.1.0-alpha.5, telemetry and analytics reporting was added in alpha.6 AFAIR.

**Comment by heypiotr** [comment]
Fixed in 1cb0721aeb29acebf3a1581b6128569f633b033b.
