### ISSUE TITLE
withScannerInForegroundService doesn't work

### ISSUE THREAD

**Issue by heypiotr** [Estimote/Xamarin-Bindings#5]
On Android, we can tell the Proximity SDK to run the scanning in a foreground service, which keeps the scanning even if the user isn't interacting with the app. This works fine in native Android apps, but for some reason doesn't work with these Xamarin bindings.

First reported by @MatthewGerber here: https://github.com/Estimote/Xamarin-Bindings/issues/4#issuecomment-384663432

I managed to reproduce this on my Nexus 5X w/ Android 8.1.

TBD! (To Be Debugged :wink:)

**Comment by heypiotr** [comment]
@MatthewGerber, you said that the example app worked for you … did you uncomment this line?

https://github.com/Estimote/Xamarin-Bindings/blob/master/ExampleApps/Example.Android.Proximity/MainActivity.cs#L60

I tried running the example app with this line uncommented, and then it doesn't work for me either.

**Comment by MatthewGerber** [comment]
@heypiotr I got everything to work with the above fix, but not right away. After building the Estimote binding DLLs and adding a reference in my app to the Android DLL, I got a compile-time error in my app about a conflict with a duplicate manifest entry for the v26 support library. I removed the following files from the bindings project:

````
Estimote.Android.Proximity/Jars/support-annotations-27.1.1.jar
Estimote.Android.Proximity/Jars/support-compat-26.1.0.aar.classes.jar
Estimote.Android.Proximity/Jars/support-core-utils-26.1.0.aar.classes.jar
````

Having done this, the bindings project builds as does my app, and my app scans for beacons using the foreground service. Everything looks fine.

Does this sound right to you? Is this something you need to fix?

**Comment by heypiotr** [comment]
Huh, interesting. I was able to reproduce it after a full clean and updating VS. For now, I just removed these from the binding, and added info to README to instead include these support packages in the app itself. (I think they're actually there by default?)
