### ISSUE TITLE
Eddystone beacon scanning

### ISSUE THREAD

**Issue by PaulVrugt** [Estimote/Xamarin-Bindings#6]
Hello,

We tried to use the estimote sdk for iOS generated by xamarin (https://components.xamarin.com/view/estimotesdkios)

However, this components give some weird issue when a eddybeacon is found. It seems there is something wrong with the binding, because the returned value in the eventargs of the DiscoveredEddystones method seems to wrong at runtime.

So, I thought I'd give this example a go. However, it seems that the xamarin bindings doesn't support eddystone scanning. Does the proximity and bluetooth scanning sdk included in this project support this? And what do i need to do to be able to use it?

**Comment by heypiotr** [comment]
Hey Paul, thanks for the interest in these bindings. At this time we have no plans to add Eddystone support to our new Proximity SDKs, and by extension, to these Xamarin bindings. Is Eddystone a hard requirement for you? Would you consider switching to Estimote Monitoring? (it's the tech/broadcasting that powers our Proximity SDKs)

**Comment by PaulVrugt** [comment]
@heypiotr 

Thanks for the quick reply!

The only thing we want to do is detect nearby beacons. And identify them using the namespace and instance, and be able to determine how close the beacon is. This was easy using eddystone, therefore we went with this. We can also set the beacons to a different technology. We're not interested in using the estimote cloud or anything right now.

If this is possible with the current bindings using a different technology, that would also fix our issue.

If so, could you point me to a simple example on how to do this?
