### ISSUE TITLE
Create a NuGet package

### ISSUE THREAD

**Issue by OscarCanek** [Estimote/Xamarin-Bindings#7]
I download the demo and work fine for me but I have some issues due to updates or hotfixes so I search for a NuGet package of this bindings and I found it, but the last update of the package was on october 19 2017. 
- Could you please update the NuGet package to use the latest updates made to native libs? 
- Wich version of native libs are used in this bindings?

This is what I found:

![image](https://user-images.githubusercontent.com/3521524/41062153-216a59e4-6992-11e8-995b-26fb304e7458.png)

**Comment by heypiotr** [comment]
These packages are not ours, they were built by the Xamarin team. Their code base is here:

https://github.com/xamarin/XamarinComponents/tree/master/XPlat/Estimote

That is, putting our own bindings on NuGet is definitely something we should do, so I'll leave this issue open as a reminder/TODO item (:

**Comment by saamerm** [comment]
Its been a few months, any updates on this @heypiotr ?

**Comment by MatthewGerber** [comment]
@heypiotr Related to this:  Are there plans to release Xamarin iOS/Android bindings for the Indoor and Robotics SDKs?

**Comment by saamerm** [comment]
I found this https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/quickstart/create-and-publish-a-package-using-visual-studio-net-framework.md that made it seem straight forward
I see a big push towards using beacons in North America, even though it may seem old technology for some (5 years), and Estimote Inc. is a big name in the developer's preference because of your documentation. So please continue! 👍

**Comment by saamerm** [comment]
@heypiotr that sounds awesome, just in time when I get my hands at the new estimotes I bought 😄 

Have you seen any implementations of these libraries with Xamarin Forms?

**Comment by heypiotr** [comment]
Done:

https://www.nuget.org/packages/Estimote.iOS.Proximity/
https://www.nuget.org/packages/Estimote.Android.Proximity/

AFAIK, Xamarin Forms is just a UI framework for Xamarin for building cross-platform UIs. (i.e., build a UI once, use it on iOS + Android + Windows) Is that correct? In which case, I don't think it has anything to do with Estimote SDKs. Maybe I'm misunderstanding something though, let me know (:

[maybe we could move that conversation to https://forums.estimote.com though, or to another issue as a "feature request"]

**Comment by MatthewGerber** [comment]
Yes, excellent work. Thank you so much. I agree that use of these SDKs shouldn't differ from native Android to XF UI frameworks.
