### ISSUE TITLE
EstimoteProximitySDK  is missing (Failed to add in a project)

### ISSUE THREAD

**Issue by eduardoguilarducci** [Estimote/Xamarin-Bindings#8]
I just downloaded the sample run, and it works fine!

But when I tried to add the project and reference to my own project, Im receiving and error and the app crashs.

The Application Output window show this message:

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/5A813272-5B92-419C-A5A0-D25A332B61B2/**MyAppName**/Frameworks/EstimoteProximitySDK.framework/EstimoteProximitySDK
  Reason: image not found

**Comment by eduardoguilarducci** [comment]
I just cleaned the BIN and OBJ folders of the sample app and the app stops working and get the same error...

**Comment by eduardoguilarducci** [comment]
Solved adding explicity the packages in the projects, besides the packages.json

thanks

**Comment by greemlin** [comment]
@heypiotr I downloaded the XamarinBindings. The Android Example app is missing the using Estimote.Android.Proximity reference . It resolves Estimote.Android but not Proximity. I tried to build the included Estimote.Android.Proximity which builds ok and rereference it in the Android solution. No luck. Any suggestions?

**Comment by OllieStrevel** [comment]
The Xamarin Android Binding has the Android SDK v0.5.1 jar, current version is 0.6.0.

**Comment by heypiotr** [comment]
It's not a completely trivial update, as there are some API-breaking changes in Android SDK 0.6.0—so I just need to find a moment to do the update and make sure everything still works. I'm currently on the road, so I'll probably get to it on Friday at the earliest. Feel free to open a new issue to track the progress.

**Comment by OllieStrevel** [comment]
Thanks for your reply! In this version the Minor, Major concept is deprecated versus the Proximity Zone & Tags concept right? I cannot find this information no where. 
The only identifiers information, is the Device ID?

Thanks for your answer :)
