### ISSUE TITLE
EstimoteBluetoothScannerFactory no found

### ISSUE THREAD

**Issue by OscarCanek** [Estimote/Xamarin-Bindings#9]
After update to `proximity-sdk-0.5.1.aar` I'm getting the following error:

```
Java.Lang.NoClassDefFoundError: 
Failed resolution of: Lcom/estimote/scanning_plugin/api/EstimoteBluetoothScannerFactory;
```

> Line 90 of the Estimote.Android.Proximity.IProximityObserver.cs file

Why I'm getting this error, how can I fix it?

**Comment by heypiotr** [comment]
I've tested your PR (#10) and it worked fine for me, did you manage to overcome this problem?

**Comment by OscarCanek** [comment]
Yes, the update I did was the following:

https://github.com/OscarCanek/Xamarin-Bindings/blob/bd4ce8fd8daf0138e1520ae4d1c51270811884da/Estimote.Android.Proximity/Scripts/build.gradle#L7-L8
